### ISSUE TITLE
Sequential/step mode

### ISSUE THREAD

**Issue by bblais** [Nico-Curti/NumPyNet#3]
Is there a preferred way to do a sequential mode for training?  I think I can just set batch=1, the input vector to a 1-sample matrix, etc...  not sure if this will cause issues if I try. 

(trying to use the neural network to do deep-q learning, which updates 1-input vector at a time).

**Comment by Nico-Curti** [comment]
I've never used a q-Learning model so I probably can't give you the right advise. Theoretically, if you need to provide your data one-by-one to a model you can use a batch size equal to 1 and an input properly reshaped. It should work. Obviously if you find any issue, please tell me and I will provide you a fix asap.
From a computational performance point of view, it is probably possible to obtain a more efficient model by using the "low level" functions of the package. Instead using just the fit function, you can write your version of the training function by combining the forward+backward+update methods more efficiently according to your needs.

Pay attention to some layer types: not the whole set of layer types has been tested yet! RNN, SimpleRNN, GRU, LSTM, and Yolo are still broken so you can't use them in your model.
