### ISSUE TITLE
Simple Linear Regression Network not working

### ISSUE THREAD

**Issue by bblais** [Nico-Curti/NumPyNet#4]
So I'm just testing out some simple networks, like the one below for doing linear regression.  Perhaps I'm missing something, but when I call the model.fit() it only prints Epoch 1/1000 and doesn't run anything.

```python
# make some fake data
m_0, m_1 = 1.1, 2.1
intercept = bias = 3.1
coefficients = np.array([[m_0, m_1]])

x_obs=20*rand(200,2)-10
y_obs = (x_obs @ coefficients.T) + bias  + randn(*y_obs.shape)*0.5


X,y=x_obs,y_obs
num_samples, input_size = X.shape


# Reshape the data according to a 4D tensor
X = X.reshape(num_samples, 1, 1, input_size)
y = y.reshape(num_samples,1,1,-1)
batch=num_samples


# build the model
model = Network(batch=input_size, 
                input_shape=(1,1,input_size))

model.add(Connected_layer(outputs=1, activation='Linear'))
model.add(Cost_layer(cost_type='mse'))
model.compile(optimizer=Adam(lr=0.001), 
            metrics=[mean_accuracy_score])
model.batch=batch

model.fit(X=X, y=y, max_iter=1000,verbose=True)
```

**Comment by Mat092** [comment]
Hello! 

So apparently the argument ``verbose=True`` in ``model.fit(...)`` flushes away any error resulting from the fitting. By setting ``verbose=False`` the method ``fit`` raises:
```python
ValueError: operands could not be broadcast together with shapes (2,1,1,1) (200,1,1,1) (2,1,1,1) 
```
which is caused by the line 
```python
model.batch = batch
```
If you'd like to use a batch size of 200 (num_samples), it is recommended to initialize the model as:

```python
model = Network(batch=num_samples, input_shape=(1, 1, input_size))
```
This should produce the correct result, but if the problem persist, please don't hesitate to ask.

Thanks you very much for the feedback!
Mattia

**Comment by bblais** [comment]
Thanks!

From: Mattia Ceccarelli ***@***.***>
Date: Wednesday, May 17, 2023 at 06:32
To: Nico-Curti/NumPyNet ***@***.***>
Cc: Brian Blais ***@***.***>, Author ***@***.***>
Subject: Re: [Nico-Curti/NumPyNet] Simple Linear Regression Network not working (Issue #4)

Hello!

So apparently the argument verbose=True in model.fit(...) flushes away any error resulting from the fitting. By setting verbose=False the method fit raises:

ValueError: operands could not be broadcast together with shapes (2,1,1,1) (200,1,1,1) (2,1,1,1)

which is caused by the line

model.batch = batch

If you'd like to use a batch size of 200 (num_samples), it is recommended to initialize the model as:

model = Network(batch=num_samples, input_shape=(1, 1, input_size))

This should produce the correct result, but if the problem persist, please don't hesitate to ask.

Thanks you very much for the feedback!
Mattia
