### ISSUE TITLE
No module named 'parser' error

### ISSUE THREAD

**Issue by bblais** [Nico-Curti/NumPyNet#5]
`File ~/Documents/Git/NumPyNet/NumPyNet/NumPyNet/__init__.py:18
     15 from .image_utils import image_utils
     16 from .network import Network
---> 18 import parser
     19 from . import rnn_utils
     20 from .utils import print_statistics

ModuleNotFoundError: No module named 'parser'`

Seems like a simple local-import problem?  I'll see if I can solve it myself, but if you happen to fix it before me so much the better.  :)

**Comment by Nico-Curti** [comment]
Hi @bblais,
The error should be quickly fixed by changing the line to

```python
from . import parser
```

We will fix it asap in the next commits ;)

**Comment by Mat092** [comment]
Hi @bblais, hi @Nico-Curti 

Thanks for the feedback :)
commit abd111c should have solved the issue

Kind regards,
Mattia
